'use strict';

import {StyleSheet} from 'react-native';

module.exports = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column',
        backgroundColor: '#3e3a39',
    },
    sections: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: '#ffffff',
        fontSize: 12,
        fontWeight: '600',
        margin: 12,
        padding: 12,
        textAlign: 'right',
        justifyContent: 'space-between',
    },
    betSection: {
        flex: 0,
        flexDirection: 'row',
        backgroundColor: '#ffffff',
        fontSize: 12,
        fontWeight: '600',
        margin: 12,
        padding: 12,
        textAlign: 'right',
        justifyContent: 'space-between',
    },
    buttonCollector: {
        flex: 0,
        flexDirection: 'row',
        margin: 12,
    },
    buttonCollectorBig: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        height: 40,
        margin: 20,
    },
    buttonsModifyMain: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        height: 40,
        marginLeft: 20,
        marginRight: 20,
        marginBottom: 10,
        marginTop: 10,
    },
    buttonGeneric: {
        backgroundColor: '#232121',
        borderRadius: 5,
        flexDirection: 'row',
        alignItems: 'center',
        height: 40,
        paddingLeft: 140,
        paddingRight: 140,
        // justifyContent: 'center',
    },
    buttonGenericSmall: {
        flex: 1,
        flexDirection: 'row',
        fontWeight: '600',
        margin: 4,
        padding: 12,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        backgroundColor: '#232121',
        height: 40,
    },
    buttonFees: {
        backgroundColor: '#232121',
        borderRadius: 5,
        flexDirection: 'row',
        alignItems: 'center',
        height: 40,
        margin: 15,
        justifyContent: 'center',
    },
    buttonMarkets: {
        backgroundColor: '#232121',
        borderRadius: 5,
        flexDirection: 'row',
        alignItems: 'center',
        height: 40,
        margin: 15,
        justifyContent: 'center',
    },
    buttonLogOut: {
        backgroundColor: '#232121',
        borderRadius: 5,
        height: 40,
        paddingLeft: 5,
        paddingRight: 5,
        justifyContent: 'center',
        marginTop: 10,
        marginRight: 10,
    },
    textButtons: {
        fontSize: 20,
        fontWeight: '600',
        color: 'white',
    },
    textSections: {
        fontSize: 16,
        fontWeight: '600',
        color: 'black',
    },
    logo: {
        flex: 0,
        flexDirection: 'column',
        alignItems: 'center',
        marginTop: 15,
        marginBottom: 50,
    },
    logoLogOut: {
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        marginBottom: 50,
        marginTop: 15,
    },
    inputPosition: {
        flex: 2,
        flexDirection: 'column',
        alignItems: 'center',
    },
    inputFeatures: {
        color: 'black',
        borderWidth: 2,
        borderColor: '#9c9c9c',
        borderRadius: 5,
        backgroundColor: 'white',
    },
    register: {
        color: 'white',
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
        flexDirection: 'column',
        paddingBottom: 20,
    },
    filtered: {
        flexDirection: 'column-reverse',
        borderColor: 'white',
        marginTop: 30,
        marginLeft: 5,
    },
    filteredMarket: {
        flexDirection: 'row',
        borderColor: 'white',
        marginTop: 30,
        marginLeft: 5,
        marginRight: 5,
        justifyContent: 'space-between',
    },
    headerReportUser: {
        flex: 0,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: 'white',
        alignContent: 'stretch',
        justifyContent: 'space-between',
    },
    textoReportUser: {
        fontSize: 18,
        color: 'white',
        alignItems: 'center',
        justifyContent: 'center',
    }
});
